# Generated by Django 4.1.7 on 2023-02-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('pub_data', models.DateTimeField(verbose_name='发布日期')),
                ('data', models.TextField(max_length=200, verbose_name='文章内容')),
            ],
        ),
    ]
