# Generated by Django 4.1.7 on 2023-02-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
